#!/bin/bash
#chkconfig:2345 82 50
#description:Modelingtool
#processname:modeling


#source
. /etc/init.d/functions

SERVICE_NAME=modeling tool backend
PATH_TO_JAR=/root/wp2/ModelingTool_Deploy
JARNAME=`ls /root/wp2/ModelingTool_Deploy|grep ModelingTool_Backend`
PID_PATH_NAME=/var/run/model.pid

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
	    cd $PATH_TO_JAR
            nohup java -jar $JARNAME >> model`date +%Y%m%d%H%M%S`.out 2>&1 &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
	    cd $PATH_TO_JAR
            nohup java -jar $JARNAME >> model`date +%Y%m%d%H%M%S`.out 2>&1 &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac
